'use strict';
const assert = require('node:assert/strict');
const { EventEmitter } = require('node:events');
process.env.SOFIA_THIRD_FLOOR_TELEMETRY = '1';
process.env.SOFIA_OPS_EVENT_TOKEN = 'local-test-token';
const bridge = require('./telemetry-bridge.cjs');
const ingress = (runId, sequence, status) => {
  const req = new EventEmitter();
  Object.assign(req, { method: 'POST', url: '/api/sofia-ops/events/third-floor', headers: { authorization: 'Bearer local-test-token', 'content-type': 'application/json' }, resume() {} });
  const res = { code: 0, result: null, writeHead(code) { this.code = code; }, end(body) { this.result = JSON.parse(body); } };
  assert.equal(bridge.handleIngress(req, res), true);
  req.emit('data', Buffer.from(JSON.stringify({ id: `${runId}-${sequence}`, agentId: 'main', runId, sequence, source: 'n8n', floorId: 'dev-third', status, ignored: 'never retained' })));
  req.emit('end');
  assert.equal(res.code, 202);
  return res.result.accepted;
};
assert.equal(ingress('run-a', 1, 'workflow.running'), true);
assert.equal(ingress('run-a', 1, 'workflow.running'), false);
assert.equal(ingress('run-a', 2, 'workflow.completed'), true);
assert.equal(ingress('run-a', 3, 'workflow.failed'), false);
assert.equal(ingress('run-a', 4, 'workflow.running'), false);
assert.equal(ingress('run-b', 1, 'workflow.running'), true);
assert.equal(ingress('run-a', 5, 'workflow.failed'), false);
const socket = new EventEmitter();
const frames = [];
Object.assign(socket, { readyState: 1, bufferedAmount: 0, send(raw) { frames.push(JSON.parse(raw)); } });
assert.equal(bridge.authenticate(socket, { type: 'hello-ok', auth: { role: 'operator', scopes: ['operator.read'] } }), true);
assert.equal(frames.length, 1);
assert.equal(frames[0].payload.runId, 'run-b');
assert.equal(frames[0].payload.ignored, undefined);
assert.equal(ingress('run-b', 2, 'workflow.failed'), true);
assert.equal(ingress('run-b', 3, 'workflow.completed'), false);
console.log('PASS: immutable terminals, sequence deduplication, late-run rejection, latest-only replay and metadata allowlist');
